### ISSUE TITLE
MAC problem (but i use your repo)

### ISSUE THREAD

**Issue by vampywiz17** [pauln/esphome-linp-doorbell-g03#24]
Hello there!

I use you repo from platformio, but i get this after flash:

`system_api: Base MAC address from BLK0 of EFUSE CRC error, efuse_crc = 0xe6; calc_crc = 0x55`

my config:

```
esphome:
  name: csengo
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    platform: espressif32@1.11.0
    platform_packages: 
      - framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.6

external_components:
  - source: github://vampywiz17/esphome-linp-doorbell-g03@feature/external_components
    components: [ linp_doorbell ]

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Csengo Fallback Hotspot"
    password: "****"

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:
  password: "***"

sensor:
  - platform: linp_doorbell
    volume:
      name: "Doorbell volume"
    chime_playing:
      name: "Doorbell playing tune"
#    use_old_service_names: True

captive_portal:
```

**Comment by vampywiz17** [comment]
This changes is solved :)

```
esphome:
  name: csengo
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    platform: espressif32@3.2.0
    platform_packages:
       - framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.6

external_components:
  - source: github://vampywiz17/esphome-linp-doorbell-g03@feature/external_components
    components: [ linp_doorbell ]

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Csengo Fallback Hotspot"
    password: "***"

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:
  password: "***"

sensor:
  - platform: linp_doorbell
    volume:
      name: "Doorbell volume"
    chime_playing:
      name: "Doorbell playing tune"
#    use_old_service_names: True

captive_portal:

```
